[window]
decorations = "None"
padding = { x = 2, y = 2 }
option_as_alt = "Both"

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[shell]
program = "/bin/zsh"
args = ["--login"]

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#002b36"
foreground = "#839496"

[colors.normal]
black   = "#073642"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#eee8d5"

[colors.bright]
black   = "#002b36"
red     = "#cb4b16"
green   = "#586e75"
yellow  = "#657b83"
blue    = "#839496"
magenta = "#6c71c4"
cyan    = "#93a1a1"
white   = "#fdf6e3"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"
